Update pipeline resilience-framework-pipeline

diff --git a/.harness/orgs/default/projects/test/pipelines/resilienceframeworkpipeline.yaml b/.harness/orgs/default/projects/test/pipelines/resilienceframeworkpipeline.yaml
--- a/.harness/orgs/default/projects/test/pipelines/resilienceframeworkpipeline.yaml
+++ b/.harness/orgs/default/projects/test/pipelines/resilienceframeworkpipeline.yaml
@@ -94,16 +94,29 @@ pipeline:
                     outputVariables: []
                   timeout: 10m
               - step:
-                  type: Http
-                  name: Http_1
-                  identifier: Http_1
+                  type: ShellScript
+                  name: ShellScript_2
+                  identifier: ShellScript_2
                   spec:
-                    url: http://sample-app.resilience-demo.svc.cluster.local:5000/health
-                    method: GET
-                    headers: []
-                    inputVariables: []
+                    shell: Bash
+                    executionTarget: {}
+                    source:
+                      type: Inline
+                      spec:
+                        script: |-
+                          score=95
+
+                          echo "Current Score: $score"
+
+                          if [ $score -lt 90 ]; then
+                              echo "Assessment Failed"
+                              exit 1
+                          fi
+
+                          echo "Assessment Passed"
+                    environmentVariables: []
                     outputVariables: []
-                  timeout: 30m
+                  timeout: 10m
         tags: {}
     - stage:
         name: testdeploy
